export const GITHUB_ACTIVITY_UPSTREAM_FRESH_SECONDS = 30;
export const GITHUB_ACTIVITY_CLIENT_REFRESH_SECONDS = 30;
export const GITHUB_ACTIVITY_STALE_SECONDS = 3_600;
export const GITHUB_ACTIVITY_INSTANCE_FRESH_MS = 25_000;
export const GITHUB_ACTIVITY_RETRY_BASE_MS = 30_000;
export const GITHUB_ACTIVITY_RETRY_MAX_MS = 5 * 60_000;
